/*
 * $Id$
 *
 * Copyright (c) 1998-2008 John Morrison.
 *
 * This program is free software; you can redistribute it and/or modify
 * it under the terms of the GNU General Public License as published by
 * the Free Software Foundation; either version 2 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 */


/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "../../bolo/global.h"
#include "../../bolo/network.h"
#include "dialognetworkinfo.h"

/* Labels */
GtkWidget *lblServerAddress;
GtkWidget *lblGameAddress;
GtkWidget *lblPing;
GtkWidget *lblPPS;
GtkWidget *lblStatus;
GtkWidget *lblErrors;
GtkWidget *dialogNetworkUs;
/* Timer */
int timerNetworkInfo;


/*********************************************************
*NAME:          dialogNetInfoUpdate
*AUTHOR:        John Morrison
*CREATION DATE: 3/3/99
*LAST MODIFIED: 1/9/99
*PURPOSE:
* Updates the network info dialog box
*
*ARGUMENTS:
*  hWnd - The dialog window handle
*********************************************************/
gint dialogNetInfoUpdate(gpointer data) {
  int ping;               /* Downstream delay */
  int ppsec;              /* Packets per second */
  int numErrors;          /* Number of errors */
  char str[FILENAME_MAX]; /* Strings to display */

  /* Get addresses */
  netGetServerAddressStr(str);
  gtk_label_set_text(GTK_LABEL(lblServerAddress), str);

  /* Get data */
  netGetStats(str, &ping, &ppsec, &numErrors);
  /* Print data items */
  gtk_label_set_text(GTK_LABEL(lblStatus), str);
  sprintf(str, "%i", ping);
  gtk_label_set_text(GTK_LABEL(lblPing), str);
  sprintf(str, "%i", ppsec);
  gtk_label_set_text(GTK_LABEL(lblPPS), str);
  sprintf(str, "%i", numErrors);
  gtk_label_set_text(GTK_LABEL(lblErrors), str);
  return TRUE;
}

void windowNetworkInfoClose();

gint dialogNetworkInfoClose(GtkWidget *widget, gpointer gdata) {
  g_source_remove(timerNetworkInfo);
  windowNetworkInfoClose();
  return FALSE;
}


GtkWidget*
dialogNetworkInformationCreate(void)
{
  GtkWidget *dialogNetworkInformation;
  GtkWidget *vbox1;
  GtkWidget *hbox13;
  GtkWidget *hbox14;
  GtkWidget *label31;
  GtkWidget *hbox15;
  GtkWidget *label33;
  GtkWidget *hbox16;
  GtkWidget *label35;
  GtkWidget *hbox17;
  GtkWidget *label37;
  GtkWidget *hbox18;
  GtkWidget *label41;
  GtkWidget *label29;
  char str[FILENAME_MAX]; /* Strings to display */

  dialogNetworkInformation = gtk_dialog_new();
  g_object_set_data (dialogNetworkInformation, "dialogNetworkInformation", dialogNetworkInformation);
  gtk_widget_set_size_request (dialogNetworkInformation, 300, 150);
  gtk_container_set_border_width (GTK_CONTAINER (dialogNetworkInformation), 15);
  gtk_window_set_title (GTK_WINDOW (dialogNetworkInformation), "LinBolo Network Information");
  gtk_window_set_resizable (GTK_WINDOW (dialogNetworkInformation), FALSE);
  vbox1 = gtk_vbox_new (FALSE, 0);
  g_object_ref (vbox1);
  gtk_container_child_set (vbox1, dialogNetworkInformation, "vbox1");
  gtk_widget_show (vbox1);
  gtk_container_add (GTK_CONTAINER (dialogNetworkInformation), vbox1);

  hbox13 = gtk_hbox_new (FALSE, 0);
  g_object_ref (hbox13);

  gtk_container_child_set (hbox13, dialogNetworkInformation, "hbox13");
  gtk_widget_show (hbox13);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox13, TRUE, TRUE, 0);

  label29 = gtk_label_new ("Server Addresss: ");
  g_object_ref (label29);

  gtk_container_child_set (label29, dialogNetworkInformation, "label29");
  gtk_widget_show (label29);
  gtk_box_pack_start (GTK_BOX (hbox13), label29, FALSE, FALSE, 0);

  lblServerAddress = gtk_label_new ("");
  g_object_ref (lblServerAddress);

  gtk_container_child_set (lblServerAddress, dialogNetworkInformation, "lblServerAddress");
  gtk_widget_show (lblServerAddress);
  gtk_box_pack_end (GTK_BOX (hbox13), lblServerAddress, FALSE, FALSE, 0);

  hbox14 = gtk_hbox_new (FALSE, 0);
  g_object_ref (hbox14);

  gtk_container_child_set (hbox14, dialogNetworkInformation, "hbox14");
  gtk_widget_show (hbox14);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox14, TRUE, TRUE, 0);

  label31 = gtk_label_new ("This game address");
  g_object_ref (label31);

  gtk_container_child_set (label31, dialogNetworkInformation, "label31");
  gtk_widget_show (label31);
  gtk_box_pack_start (GTK_BOX (hbox14), label31, FALSE, FALSE, 0);

  lblGameAddress = gtk_label_new ("");
  g_object_ref (lblGameAddress);

  gtk_container_child_set (lblGameAddress, dialogNetworkInformation, "lblGameAddress");
  gtk_widget_show (lblGameAddress);
  gtk_box_pack_end (GTK_BOX (hbox14), lblGameAddress, FALSE, FALSE, 0);

  hbox15 = gtk_hbox_new (FALSE, 0);
  g_object_ref (hbox15);

  gtk_container_child_set (hbox15, dialogNetworkInformation, "hbox15");
  gtk_widget_show (hbox15);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox15, TRUE, TRUE, 0);

  label33 = gtk_label_new ("Server ping (ms) ");
  g_object_ref (label33);

  gtk_container_child_set (label33, dialogNetworkInformation, "label33");
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox15), label33, FALSE, FALSE, 0);

  lblPing = gtk_label_new ("");
  g_object_ref (lblPing);

  gtk_container_child_set (lblPing, dialogNetworkInformation, "lblPing");
  gtk_widget_show (lblPing);
  gtk_box_pack_end (GTK_BOX (hbox15), lblPing, FALSE, FALSE, 0);

  hbox16 = gtk_hbox_new (FALSE, 0);
  g_object_ref (hbox16);

  gtk_container_child_set (hbox16, dialogNetworkInformation, "hbox16");
  gtk_widget_show (hbox16);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox16, TRUE, TRUE, 0);

  label35 = gtk_label_new ("Packets per second (per player)");
  g_object_ref (label35);

  gtk_container_child_set (label35, dialogNetworkInformation, "label35");
  gtk_widget_show (label35);
  gtk_box_pack_start (GTK_BOX (hbox16), label35, FALSE, FALSE, 0);

  lblPPS = gtk_label_new ("");
  g_object_ref (lblPPS);

  gtk_container_child_set (lblPPS, dialogNetworkInformation, "lblPPS");
  gtk_widget_show (lblPPS);
  gtk_box_pack_end (GTK_BOX (hbox16), lblPPS, FALSE, FALSE, 0);

  hbox17 = gtk_hbox_new (FALSE, 0);
  g_object_ref (hbox17);

  gtk_container_child_set (hbox17, dialogNetworkInformation, "hbox17");
  gtk_widget_show (hbox17);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox17, TRUE, TRUE, 0);

  label37 = gtk_label_new ("Network status");
  g_object_ref (label37);

  gtk_container_child_set (label37, dialogNetworkInformation, "label37");
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox17), label37, FALSE, FALSE, 0);

  lblStatus = gtk_label_new ("");
  g_object_ref (lblStatus);

  gtk_container_child_set (lblStatus, dialogNetworkInformation, "lblStatus");
  gtk_widget_show (lblStatus);
  gtk_box_pack_end (GTK_BOX (hbox17), lblStatus, FALSE, FALSE, 0);

  hbox18 = gtk_hbox_new (FALSE, 0);
  g_object_ref (hbox18);

  gtk_container_child_set (hbox18, dialogNetworkInformation, "hbox18");
  gtk_widget_show (hbox18);
  gtk_box_pack_start (GTK_BOX (vbox1), hbox18, TRUE, TRUE, 0);

  label41 = gtk_label_new ("Network errors");
  g_object_ref (label41);

  gtk_container_child_set (label41, dialogNetworkInformation, "label41");
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox18), label41, FALSE, FALSE, 0);

  lblErrors = gtk_label_new ("");
  g_object_ref (lblErrors);

  gtk_container_child_set (lblErrors, dialogNetworkInformation, "lblErrors");
  gtk_widget_show (lblErrors);
  gtk_box_pack_end (GTK_BOX (hbox18), lblErrors, FALSE, FALSE, 0);

  timerNetworkInfo = g_timeout_add(250/* SECOND */, dialogNetInfoUpdate, (gpointer) NULL);
  g_signal_connect(dialogNetworkInformation, "delete_event", G_CALLBACK(dialogNetworkInfoClose), NULL);

  netGetOurAddressStr(str);
  gtk_label_set_text(GTK_LABEL(lblGameAddress), str);
  dialogNetInfoUpdate(NULL);
  dialogNetworkUs = dialogNetworkInformation;
  return dialogNetworkInformation;
}
